---
- name: "Laboratorio de Delegates. Nodo01"
  hosts: 172.17.149.120
  tasks:
    - name: "Consultar hora actual"
      command: "date +%T"
      register: hora_actual

    - name: "Cambiar la zona horaria"
      timezone:
        name: "Europe/Moscow"
      register: cambio_zona_horaria
    
    - name: "Fichero de datos horarios"
      file:
        path: "/tmp/datos_horarios_{{ ansible_facts['hostname'] }}"
        state: touch

    - name: "Consultar nueva hora"
      command: "date +%T"
      register: hora_nueva
    
    - name: "Registrar horas"
      lineinfile:
        path: "/tmp/datos_horarios_{{ ansible_facts['hostname'] }}"
        line: |
          La zona horaria antes del cambio era {{ cambio_zona_horaria.diff.before.name }} y la hora era {{ hora_actual.stdout_lines }}
          La zona horaria despues del cambio es {{ cambio_zona_horaria.diff.after.name }} y la hora es {{ hora_nueva.stdout_lines }}

    - name: "Vuelta atras"
      timezone:
        name: "{{ cambio_zona_horaria.diff.before.name }}"

- name: "Laboratorio de Delegates. Nodo02"
  hosts: 172.17.149.125
  tasks:
    - name: "Consultar hora actual"
      command: "date +%T"
      register: hora_actual

    - name: "Cambiar la zona horaria"
      timezone:
        name: "Asia/Tokyo"
      register: cambio_zona_horaria
    
    - name: "Fichero de datos horarios"
      file:
        path: "/tmp/datos_horarios_{{ ansible_facts['hostname'] }}"
        state: touch

    - name: "Consultar nueva hora"
      command: "date +%T"
      register: hora_nueva
    
    - name: "Registrar horas"
      lineinfile:
        path: "/tmp/datos_horarios_{{ ansible_facts['hostname'] }}"
        line: |
          La zona horaria antes del cambio era {{ cambio_zona_horaria.diff.before.name }} y la hora era {{ hora_actual.stdout_lines }}
          La zona horaria despues del cambio es {{ cambio_zona_horaria.diff.after.name }} y la hora es {{ hora_nueva.stdout_lines }}

    - name: "Vuelta atras"
      timezone:
        name: "{{ cambio_zona_horaria.diff.before.name }}"

- name: "Desacargar los ficheros generados"
  hosts: master
  tasks:
    - name: "Copiamos a master"
      synchronize: "src=/tmp/datos_horarios_nodo02 dest=/tmp/datos_horarios_nodo02"
      delegate_to: 172.17.149.125

...